name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: 'Features'
      labels:
          - 'feature'
      title-regex: "(.*)"
    - title: 'Bug Fixes'
      labels:
          - 'bug'
      title-regex: "(.*)"
    - title: 'Internal'
      labels:
          - 'internal'
          - 'tech_debt'
          - 'documentation'
      title-regex: "(.*)"
exclude-labels:
    - 'skip-changelog'
template: |
    ## What's changed

    $CHANGES
    {{#each categories}}
    ## {{title}}
    {{#each issues}}
    - {{convert issue}}
    {{/each}}
    {{/each}}
