name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
category-template: '[int]'
categories:
    - title: 'Features'
      labels:
          - 'feature'
    - title: 'Bug Fixes'
      labels:
          - 'bug'
    - title: 'Internal'
      labels:
          - 'internal'
          - 'tech_debt'
          - 'documentation'
change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
exclude-labels:
    - 'skip-changelog'
template: |
    ## What's changed

    $CHANGES
autolabeler:
    - label: 'internal'
      branch:
          - '/internal\/.+/'
    - label: 'bug'
      branch:
          - '/bug\/.+/'
    - label: 'feature'
      branch:
          - '/feature\/.+/'
