name: "Verify type labels"

on:
    pull_request:
        types: [opened, labeled, unlabeled, synchronize]

jobs:
    triage:
        runs-on: ubuntu-18.04
        steps:
            - uses: kate0/match-label-action@v2
              with:
                  allowed: 'fix, features, documentation, internal'
